Fixes && Suggestions (#3)
* Fixes the below:

```c
billard3d.c:2319:41: warning: unused variable ‘cue_start_ball’ [-Wunused-variable]
 2319 |    VMvect dir,cue_start,cue_start_bande,cue_start_ball,nx,ny,pos,hitpoint;
      |                                         ^~~~~~~~~~~~~~
billard3d.c:2319:15: warning: unused variable ‘cue_start’ [-Wunused-variable]
 2319 |    VMvect dir,cue_start,cue_start_bande,cue_start_ball,nx,ny,pos,hitpoint;
      |               ^~~~~~~~~
billard3d.c: In function ‘init_player_roster’:
billard3d.c:2574:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
 2574 |     if(getenv("USER"))
      |     ^~
billard3d.c:2576:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
 2576 |         strcpy(player[0].name,getenv("USER"));
      |         ^~~~~~
billard3d.c: In function ‘Key’:
billard3d.c:6506:25: warning: statement with no effect [-Wunused-value]
 6506 |           options_pause == 0;
      |           ~~~~~~~~~~~~~~^~~~
```

* - Fix include path for freetype2/ft2build.h
- Drop freetype2/freetypeftoutln.h as it does not exist in recent
  versions of `freetype2`

* Compiling with `FAST_MATH` using a modern GCC and LD vers results with:
```
/usr/bin/ld: billard3d.c:(.text+0x4d79): undefined reference to `fastcos'
/usr/bin/ld: billard3d.c:(.text+0x4dbe): undefined reference to `fastsin'
```

Set to `no` by default for now.

* Util script for GNU build toolchain invocation

* Synlink to MD.

* README fixes

* A few more README modifications

* .

* .

* Rearranged README sections

* A few more touches

* Illustration images

* Add images to README.

* .

* More screen images

* Add more screen images

* Added Jesse to `AUTHORS`

* CI

* .

* `libpng-dev` is the package name for recent Ubuntu versions

* invoke `configure` && `make`

* use `pkg-config` since freetype-config is deprecated.

* Creation of desktop file needs to happen before copying it

* fix typo

* fix header safeguard typo

* .

* - Same font as status for player name and score
- Show number of balls pocketed by player when player 8 ball
- Orange rather than blue for non-active player name and score
- Fix some compiler warnings
- Introduced UK English locale (mostly because of the spelling of the
  word 'colour')

* - options_language size 5 to accommodate languages with multiple locales
- use '-' as separator for locales since '_' is currently replaced by space

* bigger size

* - avoid `sprintf()` overflow warnings
- freetype/ftoutln.h is needed for `FT_Outline_Decompose()`

* be more generous with size allocation to avoid `-Wformat-overflow=` warnings

* Remove `inline` from function declarations as they are in fact defined
in `vmath.c`

---------

Co-authored-by: Jesse Portnoy <jesse@packman.io>